"""create note chunks table

Revision ID: af7facad7cf3
Revises: 7c3a85815248
Create Date: 2026-10-05 13:45:22.906147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af7facad7cf3'
down_revision: Union[str, Sequence[str], None] = '7c3a85815248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_chunks',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'chunk_index', name='uq_note_chunks_note_id_chunk_index')
    )
    op.create_index(op.f('ix_note_chunks_note_id'), 'note_chunks', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_chunks_user_id'), 'note_chunks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_chunks_user_id'), table_name='note_chunks')
    op.drop_index(op.f('ix_note_chunks_note_id'), table_name='note_chunks')
    op.drop_table('note_chunks')
    # ### end Alembic commands ###
